spring:
  application:
    name: email-service
  mvc:
    servlet:
      path: /email-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: johnathannguyen@jkn95.dev
    password: nyab sifn bcrs marn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    template:
      exchange: spring.email.message
      default-receive-queue: spring.email.queue
      routing-key: spring.email.#

server:
  port: 8080

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
