spring:
  application:
    name: email-service
#  mvc:
#    servlet:
#      path: /email-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: johnathannguyen@jkn95.dev
    password: nyab sifn bcrs marn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    ssl:
      enabled: true
    addresses: amqps://b-3f4888ba-f315-45a3-99ec-74e7afdd1d0b.mq.us-east-2.amazonaws.com:5671
    username: blogAdmin
    password: 1234adminamqp
    template:
      exchange: spring.email.message
      default-receive-queue: spring.email.queue
      routing-key: spring.email.#

server:
  port: 8080

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
